#!/usr/bin/env python3
"""Single source of compute for the Civilization Wiki's article stats and the
durable generated block in index.md.

Pure ground-truth stats (article_count + per-tier breakdown), derived from
wiki/*.md frontmatter. These are a pure function of the committed wiki/ files,
so the generated block re-renders byte-identically unless the corpus changed.
Timestamp / stale / sources counts are operational and live in the ephemeral
refresh-status.json banner, not here.
"""
import re
import pathlib

# Canonical breakdown order. Any tier value NOT listed here, and any article
# missing a `tier:` field (-> NO_TIER), is surfaced as its own bucket rather
# than folded into a default: an unexpected tier shows up, never hides.
CANONICAL_TIERS = ["foundational", "architecture", "arc",
                   "investigation", "concept", "meta"]
NO_TIER = "(no-tier)"

_TIER_RE = re.compile(r"^tier:[ \t]*(.+?)[ \t]*$", re.M)


def _frontmatter(text):
    """The YAML frontmatter block between the first two '---' fences, or ''."""
    if text.startswith("---"):
        end = text.find("\n---", 3)
        if end != -1:
            return text[3:end]
    return ""


def _tier_of(path):
    m = _TIER_RE.search(_frontmatter(path.read_text()))
    return m.group(1).strip().strip('"').strip("'") if m else NO_TIER


def compute_counts(root):
    """Pure ground-truth stats from wiki/*.md frontmatter.

    Returns {"article_count": int, "tier_counts": [(tier, count), ...]} with
    canonical tiers first (CANONICAL_TIERS order, only those present), then any
    other tier values plus NO_TIER appended in sorted order. Deterministic and
    side-effect free.
    """
    root = pathlib.Path(root)
    counts = {}
    total = 0
    for p in sorted((root / "wiki").glob("*.md")):
        tier = _tier_of(p)
        counts[tier] = counts.get(tier, 0) + 1
        total += 1
    ordered = [(t, counts[t]) for t in CANONICAL_TIERS if t in counts]
    ordered += [(t, counts[t]) for t in sorted(counts) if t not in CANONICAL_TIERS]
    assert sum(c for _, c in ordered) == total, "tier counts must sum to article_count"
    return {"article_count": total, "tier_counts": ordered}


def ensure_nonzero(counts):
    """Fail-closed guard: a zero article_count must never overwrite a real one."""
    if counts["article_count"] <= 0:
        raise ValueError("refusing to write stats: article_count is 0 "
                         "(likely a wrong path, not an empty wiki)")
    return counts


# --- generated-block markers (the writer owns ONLY what is between them) ---
BEGIN_MARKER = ("<!-- stats:begin — generated by compile/refresh.py from wiki/ "
                "frontmatter; do not hand-edit between these markers -->")
END_MARKER = "<!-- stats:end -->"

_BEGIN_RE = re.compile(r"<!--\s*stats:begin\b.*?-->", re.S)
_END_RE = re.compile(r"<!--\s*stats:end\s*-->")
_ARTICLE_COUNT_RE = re.compile(r"^(article_count:[ \t]*)(\d+)[ \t]*$", re.M)


def render_stats_line(counts):
    """The single prose line the generator owns (between the markers)."""
    breakdown = " · ".join("%d %s" % (c, t) for t, c in counts["tier_counts"])
    return ("**Article count (auto-derived from `wiki/` frontmatter):** "
            "%d — %s" % (counts["article_count"], breakdown))


def _replace_between_markers(text, new_inner):
    """Replace content between the stats markers. Fail-closed: require exactly
    one begin and one end, begin before end; otherwise raise ValueError."""
    begins = list(_BEGIN_RE.finditer(text))
    ends = list(_END_RE.finditer(text))
    if len(begins) != 1 or len(ends) != 1:
        raise ValueError("stats markers must appear exactly once each: "
                         "found %d begin, %d end" % (len(begins), len(ends)))
    b, e = begins[0], ends[0]
    if b.start() >= e.start():
        raise ValueError("stats:begin must appear before stats:end")
    return text[:b.end()] + "\n" + new_inner + "\n" + text[e.start():]


def _set_frontmatter_article_count(text, n):
    """Set the article_count line to n, scoped to the YAML frontmatter block ONLY
    (never the document body). Absent from the frontmatter -> unchanged. Present
    more than once in the frontmatter -> raise (ambiguous)."""
    if not text.startswith("---"):
        return text
    end = text.find("\n---", 3)
    if end == -1:
        return text
    fm = text[3:end]
    matches = list(_ARTICLE_COUNT_RE.finditer(fm))
    if not matches:
        return text
    if len(matches) > 1:
        raise ValueError("article_count appears %d times in frontmatter; expected at most one"
                         % len(matches))
    new_fm = _ARTICLE_COUNT_RE.sub(lambda m: "%s%d" % (m.group(1), n), fm, count=1)
    return text[:3] + new_fm + text[end:]


def write_index_block(index_path, counts):
    """Rewrite the generated block + frontmatter article_count in index.md from
    counts. Idempotent: identical counts -> identical bytes -> no write. Returns
    True if the file changed. Raises ValueError on malformed markers.

    Does NOT enforce a nonzero count — call ensure_nonzero(counts) first (the
    refresh.py orchestrator does) so a zero count can't overwrite a real one."""
    index_path = pathlib.Path(index_path)
    text = index_path.read_text()
    new_text = _replace_between_markers(text, render_stats_line(counts))
    new_text = _set_frontmatter_article_count(new_text, counts["article_count"])
    if new_text != text:
        index_path.write_text(new_text)
        return True
    return False
